### ISSUE TITLE
How to Hint language or define list of expected language

### ISSUE THREAD

**Issue by yurilla56** [Abhijit-2592/spacy-langdetect#1]
Hello, is it possible to use list of languages for detection like ["en", "wit", "da"]?

Thank you in advance.

**Comment by Abhijit-2592** [comment]
@yurilla56  This can be done. This is why we have `language_detection_function` argument in the Constructor. Write your own **custom_detection_function** and then return any python object you want. This will be stored in `doc._.language`, `span._.language`, `token._.language`
