### ISSUE TITLE
Support for SpaCy 3

### ISSUE THREAD

**Issue by maxtrem** [Abhijit-2592/spacy-langdetect#5]
Hey! I'm just wondering if there will be support for the new SpaCy version 3?

Thanks!

**Comment by davidrs** [comment]
If it helps, I think the main change needed is adding this decorator to it:
https://spacy.io/usage/v3#migrating-add-pipe

**Comment by maxtrem** [comment]
@davidrs Thanks!
I have gone now with solution using [pycld2](https://pypi.org/project/pycld2/). This is pretty fast and can also be used with the decorator you mentioned.

Thanks anyway!
